apiVersion: v1
entries:
  pc:
  - apiVersion: v1
    appVersion: V1.0
    created: "2020-10-15T11:48:01.9048916Z"
    description: '&#039;Naast deze JSON rest API is er ook een [graphql](/graphql)
      interface beschikbaar.&#039;'
    digest: 275ac3a4d606fd29f0a08e85e71e162de5bc21447687e6efcdb72354a99612db
    home: pc.zaakonline.nl
    icon: pc.zaakonline.nl
    name: pc
    urls:
    - pc-0.1.0.tgz
    version: 0.1.0
generated: "2020-10-15T11:48:01.899391Z"
